require('ar')
Ar.test()

local buf = Ar.malloc(1024)
local fd = Ar.create(buf, 1024)

Ar.writeint8(fd,  3)
Ar.writeint16(fd,  33)
Ar.writeint32(fd,  333)
Ar.writeint64(fd,  33333)
Ar.writelstr(fd,  'hello')
Ar.writestr(fd,  'world')
print('datalen', Ar.datalen(fd))
Ar.rewind(fd)
print('datalen', Ar.datalen(fd))
print(Ar.readint8(fd))
print(Ar.readint16(fd))
print(Ar.readint32(fd))
print(Ar.readint64(fd))
print(Ar.readlstr(fd))
print(Ar.readstr(fd, 5))
print('datalen', Ar.datalen(fd))
