require('libsrv')
print(Ar)
print('Ar.malloc', Ar.malloc)
local buf = Ar.malloc(1024)
local fd = Ar.create(buf, 1024)
Ar.writeint8(fd,  3)
Ar.writeint16(fd,  33)
Ar.writeint32(fd,  333)
Ar.writeint64(fd,  33333)
assert(Ar.datalen(fd) == 15)
Ar.writelstr(fd,  'hello')
assert(Ar.datalen(fd) == 22)
Ar.writestr(fd,  'world')
assert(Ar.datalen(fd) == 27)
print('datalen', Ar.datalen(fd))
Ar.rewind(fd)
assert(Ar.datalen(fd) == 0)
print('datalen', Ar.datalen(fd))
print(Ar.readint8(fd))
print(Ar.readint16(fd))
print(Ar.readint32(fd))
print(Ar.readint64(fd))
print(Ar.readlstr(fd))
print(Ar.readstr(fd, 5))
print('datalen', Ar.datalen(fd))
