all:
	cd ae;make
	cd ar;make
	cd bitpatch;make
	cd date;make
	cd file;make
	cd json;make
	cd log;make
	cd luaexe;make
	cd mysql;make
	cd pblua;make
	cd redis;make
	cd socket;make
	cd srvmain;make
	cd stringpatch;make
	cd system;make

install:
	cd ae;make install
	cd ar;make install
	cd bitpatch;make install
	cd date;make install
	cd file;make install
	cd json;make install
	cd log;make install
	cd luaexe;make install
	cd mysql;make install
	cd pblua;make install
	cd redis;make install
	cd socket;make install
	cd srvmain;make install
	cd stringpatch;make install
	cd system;make install

clean:
	cd ae;make clean
	cd ar;make clean
	cd bitpatch;make clean
	cd date;make clean
	cd file;make clean
	cd json;make clean
	cd log;make clean
	cd luaexe;make clean
	cd mysql;make clean
	cd pblua;make clean
	cd redis;make clean
	cd socket;make clean
	cd srvmain;make clean
	cd stringpatch;make clean
	cd system;make clean


