
all:
	../../bin/startsrv gatesrv1

game:
	../../bin/startsrv gamesrv1

gate:
	../../bin/srvstart gatesrv1

global:
	../../bin/startsrv globalsrv1

test:
	../../bin/pbclient login.ping

dbinit:
	../../bin/dbinit

srvlist:
	../../bin/srvlist

srvclean:
	../../bin/srvclean gamesrv1

srvstop:
	../../bin/srvstop globalsrv1
